repos:
- repo: https://github.com/Holzhaus/sourceheaders
  rev: v0.0.4
  hooks:
  - id: sourceheaders
    name: Add license headers
#    types_or:
#    - yaml
#    - shell
    files: ^docs\/.*\.(adoc|ya?ml|sh)$
