// Copyright (c) 2026 i-Cell Mobilsoft Zrt.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you
// may not use this file except in compliance with the License. You
// may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

:figure-caption!:

[[webapp]]
= Webapp

A web application with a user interface supports the management of templates and their upload into the database. Templates made up of multiple files are handled as groups, allowing the complete template to be tested as a whole. During template generation testing, the application provides detailed feedback on any errors that may occur during generation, thereby assisting troubleshooting. In the case of successful generation, the generated document can be downloaded for review. After successful generation, the template group can be loaded into the database in a single step after providing the required metadata.

It includes the following functions:

* listing, filtering, and sorting of templates
* testing document generation from the template(s) to be uploaded
* uploading a new template (group) or overwriting an existing one

Further functions that can be developed:
* editing the metadata of an existing template group
* downloading the files of an existing template group
* deleting a template group