name: Check licence

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'
  workflow_dispatch:
    inputs:
      comment:
        description: 'test check licence'
        # Default value if no value is explicitly provided
        default: 'test check licence'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  check-licence:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run license header hook
        run: pre-commit run sourceheaders --all-files --verbose || true
        env:
          ACTIONS_STEP_DEBUG: true
          ACTIONS_RUNNER_DEBUG: true

      - name: Commit added headers
        run: |
          if ! git diff --quiet; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "chore: add missing license headers"
            git push
          fi
