name: Check licence

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'
  workflow_dispatch:
    inputs:
      comment:
        description: 'test check licence'
        # Default value if no value is explicitly provided
        default: 'test check licence'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  check-licence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v4
      - name: Check the license in the files
        uses: pre-commit/action@v3.0.1
