name: Check licence

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

jobs:
  check-licence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v4
      - name: Check the license in the files
        uses: pre-commit/action@v3.0.1
